services:
  postgres:
    image: postgres:16
    container_name: postgres_shortener
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - url_shorter_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_shortener
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - url_shorter_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_shortener
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    networks:
      - url_shorter_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_shortener
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    command: sh -c "node dist/main.js"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - url_shorter_network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker_shortener
    restart: always
    env_file:
      - .env
    command: node dist/main.js
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - url_shorter_network

networks:
  url_shorter_network:
    driver: bridge

volumes:
  pgdata: